name       : perl-file-chdir
version    : 0.1011
release    : 1
source     :
    - https://cpan.metacpan.org/authors/id/D/DA/DAGOLDEN/File-chdir-0.1011.tar.gz : 31ebf912df48d5d681def74b9880d78b1f3aca4351a0ed1fe3570b8e03af6c79
homepage   : https://metacpan.org/dist/File-chdir
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : A more sensible way to change directories
description: |
     File::chdir a more sensible way to change directories
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
